### ISSUE TITLE
Error after initial run

### ISSUE THREAD

**Issue by chrisschaub** [kurumiimari/hsexplorer#18]
After I start the indexer, I get the following error ...
```
[2022-04-13 19:13:44,163] INFO in indexer: Started indexer.
[2022-04-13 19:13:44,196] INFO in indexer: Current height: 0, chain height: 115639
[2022-04-13 19:13:44,196] INFO in indexer: Indexing block 1.
[2022-04-13 19:13:44,201] ERROR in indexer: Error while indexing:
[2022-04-13 19:13:44,201] ERROR in indexer: 'NoneType' object has no attribute 'txs'
Traceback (most recent call last):
  File "hsexplorer/explorer/indexer.py", line 61, in index_blocks
    index_block(height)
  File "hsexplorer/explorer/indexer.py", line 146, in index_block
    entity_counts.txs += 1
AttributeError: 'NoneType' object has no attribute 'txs'
[2022-04-13 19:13:44,201] INFO in indexer: Indexing done, sleeping.
```
I can see the schema was created by the call to python3 manage.py db upgrade head. Ok, thanks.

**Comment by chrisschaub** [comment]
I commented out  
```
entity_counts.txs += 1
```
and it started indexing

I know this is not quite right since the web interface is complaining about similar txs errors. Something about the entity counts not working correctly. I'm running a full handshake node, but it's not totally synced yet, been running for a few hours. Maybe that's the issue? Thanks for any help.
